{{- if .Values.redis.deploy -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "propfirm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ .Release.Name }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "propfirm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "propfirm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args:
            - redis-server
            - --appendonly
            - {{ .Values.redis.appendOnly | quote }}
            {{- if .Values.redis.ioThreads }}
            - --io-threads
            - {{ .Values.redis.ioThreads | quote }}
            {{- end }}
            {{- if .Values.redis.ioThreadsDoReads }}
            - --io-threads-do-reads
            - {{ .Values.redis.ioThreadsDoReads | quote }}
            {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            exec:
              command: [sh, -c, "redis-cli ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        {{- if .Values.redis.storageClassName }}
        storageClassName: {{ .Values.redis.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "propfirm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    {{- include "propfirm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end -}}
